#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Sets up the Azure half of the Code Reviewer bot: the bot itself, its Teams
# channel, and the always-on Function that leaves what Teams says on a queue
# for Smart Terminal to read. Run from anywhere:
#
#   azure/bot-relay/setup-azure-bot.sh
#
# Re-running is safe: every value is remembered in .env.local, and nothing that
# already exists in Azure is created twice.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"
ENV_FILE="$HERE/.env.local"
touch "$ENV_FILE" && chmod 600 "$ENV_FILE"

QUEUE_NAME="teams-inbound"

# run CMD... shows the command, then runs it. A failure stops the wizard with
# Azure's own message on screen; fix it and run the wizard again.
run() { printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"; "$@"; }

# remembered KEY DEFAULT prints the saved value, or DEFAULT when there is none.
remembered() { local v; v=$(_existing "$1" || true); printf '%s' "${v:-$2}"; }

in_a_year() { date -u -v+1y '+%Y-%m-%dT%H:%MZ' 2>/dev/null || date -u -d '+1 year' '+%Y-%m-%dT%H:%MZ'; }

TOTAL_STAGES=11

banner "Azure Bot for the Code Reviewer"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Tools on this Mac"
say "The wizard drives Azure with the Azure CLI (az), and packs the Function with node and zip."
for tool in node npm zip curl; do
  command -v "$tool" >/dev/null 2>&1 || { warn "$tool is missing; install it and run the wizard again."; exit 1; }
done
if ! command -v az >/dev/null 2>&1; then
  warn "The Azure CLI is not installed."
  if command -v brew >/dev/null 2>&1 && confirm "Install it now with 'brew install azure-cli'?"; then
    run brew install azure-cli
  else
    say "Install it from https://learn.microsoft.com/cli/azure/install-azure-cli and run the wizard again."
    exit 1
  fi
fi
note "$(az version --query '"azure-cli"' -o tsv 2>/dev/null | sed 's/^/az /')"
pause "Tools are ready. Continue?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sign in to Azure"
say "Sign in with the Kubrik account that can create resources in the company subscription."
say "A browser window opens for it."
if az account show >/dev/null 2>&1 && confirm "Already signed in as $(az account show --query user.name -o tsv). Keep that?"; then
  :
else
  run az login -o none
fi
az account list --query '[].{name:name, id:id, tenant:tenantId, default:isDefault}' -o table
ask AZ_SUBSCRIPTION_ID "Subscription id to use (Enter for the default one):"
[[ -z "$AZ_SUBSCRIPTION_ID" ]] && AZ_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
run az account set --subscription "$AZ_SUBSCRIPTION_ID"
AZ_TENANT_ID=$(az account show --query tenantId -o tsv)
write_env AZ_SUBSCRIPTION_ID "$AZ_SUBSCRIPTION_ID"
write_env AZ_TENANT_ID "$AZ_TENANT_ID"
say "Making sure the subscription can create bots, functions and storage (a minute the first time)."
for ns in Microsoft.BotService Microsoft.Web Microsoft.Storage; do
  run az provider register --namespace "$ns" --wait
done
pause "Continue?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Where it lives"
say "The Function runs on the Flex Consumption plan, which only some regions offer."
note "Full list: az functionapp list-flexconsumption-locations -o table"
AZ_LOCATION=$(remembered AZ_LOCATION eastus2)
ask AZ_LOCATION "Region [$AZ_LOCATION]:"
[[ -z "$AZ_LOCATION" ]] && AZ_LOCATION=eastus2
SUFFIX=$(remembered AZ_SUFFIX "$(LC_ALL=C tr -dc 'a-z0-9' </dev/urandom | head -c 6)")
AZ_RESOURCE_GROUP=$(remembered AZ_RESOURCE_GROUP rg-smart-terminal-bot)
STORAGE_ACCOUNT=$(remembered STORAGE_ACCOUNT "stbotrelay$SUFFIX")
FUNC_APP=$(remembered FUNC_APP "func-st-bot-relay-$SUFFIX")
BOT_NAME=$(remembered BOT_NAME "bot-code-reviewer-$SUFFIX")
say ""
say "Resource group   $AZ_RESOURCE_GROUP"
say "Storage + queue  $STORAGE_ACCOUNT / $QUEUE_NAME"
say "Function App     $FUNC_APP"
say "Azure Bot        $BOT_NAME (F0, free)"
say ""
note "Expected cost: cents a month. The bot tier is free; the Function and the queue bill per use."
confirm "Create the resource group with these names?" || { say "Nothing was created."; exit 0; }
for kv in AZ_LOCATION="$AZ_LOCATION" AZ_SUFFIX="$SUFFIX" AZ_RESOURCE_GROUP="$AZ_RESOURCE_GROUP" \
          STORAGE_ACCOUNT="$STORAGE_ACCOUNT" FUNC_APP="$FUNC_APP" BOT_NAME="$BOT_NAME" QUEUE_NAME="$QUEUE_NAME"; do
  write_env "${kv%%=*}" "${kv#*=}"
done
run az group create -n "$AZ_RESOURCE_GROUP" -l "$AZ_LOCATION" -o none
pause "Continue?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Storage account and the queue"
say "The queue is the mailbox: the Function drops messages in, Smart Terminal takes them out."
if ! az storage account show -n "$STORAGE_ACCOUNT" -g "$AZ_RESOURCE_GROUP" -o none 2>/dev/null; then
  run az storage account create -n "$STORAGE_ACCOUNT" -g "$AZ_RESOURCE_GROUP" -l "$AZ_LOCATION" \
    --sku Standard_LRS --kind StorageV2 --min-tls-version TLS1_2 --allow-blob-public-access false -o none
fi
STORAGE_CS=$(az storage account show-connection-string -n "$STORAGE_ACCOUNT" -g "$AZ_RESOURCE_GROUP" --query connectionString -o tsv)
run az storage queue create -n "$QUEUE_NAME" --connection-string "$STORAGE_CS" -o none
say "Smart Terminal gets a key for this one queue only: read and remove messages, nothing else, for a year."
QUEUE_SAS_EXPIRES=$(in_a_year)
QUEUE_SAS=$(az storage queue generate-sas -n "$QUEUE_NAME" --permissions rp --expiry "$QUEUE_SAS_EXPIRES" \
  --https-only --connection-string "$STORAGE_CS" -o tsv)
write_env QUEUE_URL "https://$STORAGE_ACCOUNT.queue.core.windows.net/$QUEUE_NAME"
write_env QUEUE_SAS "$QUEUE_SAS"
write_env QUEUE_SAS_EXPIRES "$QUEUE_SAS_EXPIRES"
pause "Continue?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The bot's identity (app registration)"
say "A single-tenant app registration: the bot's id and password, valid only inside Kubrik."
BOT_APP_ID=$(remembered BOT_APP_ID "")
if [[ -n "$BOT_APP_ID" ]] && az ad app show --id "$BOT_APP_ID" -o none 2>/dev/null; then
  say "Reusing the registration from last time: $BOT_APP_ID"
else
  note "If Entra refuses because users may not register apps, ask an administrator to create a"
  note "single-tenant registration named 'Code Reviewer bot', then paste its Application (client) ID here."
  if confirm "Create the app registration now?"; then
    BOT_APP_ID=$(az ad app create --display-name "Code Reviewer bot" --sign-in-audience AzureADMyOrg --query appId -o tsv)
  else
    ask BOT_APP_ID "Application (client) ID:"
  fi
  write_env BOT_APP_ID "$BOT_APP_ID"
fi
az ad sp show --id "$BOT_APP_ID" -o none 2>/dev/null || run az ad sp create --id "$BOT_APP_ID" -o none
if [[ -n "$(_existing BOT_APP_SECRET || true)" ]]; then
  say "A client secret is already saved; keeping it."
else
  say "Creating a client secret that lasts two years. It is shown once and saved only in .env.local."
  BOT_APP_SECRET=$(az ad app credential reset --id "$BOT_APP_ID" --append --display-name smart-terminal \
    --years 2 --query password -o tsv)
  write_env BOT_APP_SECRET "$BOT_APP_SECRET"
  write_env BOT_APP_SECRET_EXPIRES "$(date -u -v+2y '+%Y-%m-%d' 2>/dev/null || date -u -d '+2 years' '+%Y-%m-%d')"
fi
pause "Continue?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The Function that receives Teams"
say "Creating the Function App, telling it the bot id and the queue, and uploading the code."
if ! az functionapp show -g "$AZ_RESOURCE_GROUP" -n "$FUNC_APP" -o none 2>/dev/null; then
  run az functionapp create -g "$AZ_RESOURCE_GROUP" -n "$FUNC_APP" --storage-account "$STORAGE_ACCOUNT" \
    --flexconsumption-location "$AZ_LOCATION" --runtime node --runtime-version 22 -o none
fi
run az functionapp config appsettings set -g "$AZ_RESOURCE_GROUP" -n "$FUNC_APP" -o none --settings \
  "RELAY_QUEUE_CONNECTION=$STORAGE_CS" "RELAY_QUEUE_NAME=$QUEUE_NAME" \
  "MicrosoftAppId=$BOT_APP_ID" "MicrosoftAppTenantId=$AZ_TENANT_ID" "RELAY_ALLOWED_CHANNELS=msteams,webchat"
PACK=$(mktemp -d)
cp -R package.json package-lock.json host.json src "$PACK/"
(cd "$PACK" && npm ci --omit=dev --no-audit --no-fund --silent && zip -qr relay.zip package.json host.json src node_modules)
run az functionapp deployment source config-zip -g "$AZ_RESOURCE_GROUP" -n "$FUNC_APP" --src "$PACK/relay.zip" -o none
rm -rf "$PACK"
FUNC_HOST=$(az functionapp show -g "$AZ_RESOURCE_GROUP" -n "$FUNC_APP" --query defaultHostName -o tsv)
BOT_ENDPOINT="https://$FUNC_HOST/api/messages"
write_env BOT_ENDPOINT "$BOT_ENDPOINT"
say "Checking it answers. An empty POST should be refused with 400."
code=000
for _ in $(seq 1 24); do
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST -H 'content-type: application/json' -d '{}' "$BOT_ENDPOINT" || true)
  [[ "$code" == 400 ]] && break
  sleep 5
done
if [[ "$code" == 400 ]]; then
  printf '  %s✓%s %s is up and refuses what is not a bot message\n' "$GREEN" "$RESET" "$BOT_ENDPOINT"
else
  warn "The endpoint answered $code after two minutes, not 400."
  note "Look at: az functionapp log deployment show -g $AZ_RESOURCE_GROUP -n $FUNC_APP"
  confirm "Continue anyway?" || exit 1
fi
pause "Continue?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The Azure Bot and its Teams channel"
if ! az bot show -g "$AZ_RESOURCE_GROUP" -n "$BOT_NAME" -o none 2>/dev/null; then
  run az bot create -g "$AZ_RESOURCE_GROUP" -n "$BOT_NAME" --app-type SingleTenant \
    --appid "$BOT_APP_ID" --tenant-id "$AZ_TENANT_ID" --endpoint "$BOT_ENDPOINT" --sku F0 -o none
else
  run az bot update -g "$AZ_RESOURCE_GROUP" -n "$BOT_NAME" --endpoint "$BOT_ENDPOINT" -o none
fi
az bot msteams show -g "$AZ_RESOURCE_GROUP" -n "$BOT_NAME" -o none 2>/dev/null \
  || run az bot msteams create -g "$AZ_RESOURCE_GROUP" -n "$BOT_NAME" -o none
printf '  %s✓%s the bot points at the Function, and Teams is switched on\n' "$GREEN" "$RESET"
pause "Continue?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "First test: Web Chat in the portal"
say "This proves the whole pipe before Teams is involved: portal → bot → Function → queue → this Mac → back."
open_url "https://portal.azure.com/#@$AZ_TENANT_ID/resource/subscriptions/$AZ_SUBSCRIPTION_ID/resourceGroups/$AZ_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/$BOT_NAME/overview"
step "In the bot's left menu, open Settings → Test in Web Chat."
step "Type: hola"
say "The wizard is watching the queue for three minutes and will answer 'Recibido: hola'."
if node scripts/drain.js --reply --wait 180; then
  step "Web Chat should now show 'Recibido: hola' from the bot."
  confirm "Did the answer arrive?" || warn "The message reached this Mac but the answer did not show; check the error above, if any."
else
  warn "Nothing arrived. Look at the Function's log for 'refused with':"
  note "Portal → $FUNC_APP → Monitoring → Log stream, and type in Web Chat again."
  confirm "Continue anyway?" || exit 1
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Put the bot in Teams"
say "Teams only knows the bot through an app package. Building it:"
TEAMS_APP_VERSION=$(remembered TEAMS_APP_VERSION 1.0.0)
write_env TEAMS_APP_VERSION "$TEAMS_APP_VERSION"
ZIP=$(node scripts/make-teams-app.js)
say "$ZIP"
open -R "$ZIP" 2>/dev/null || true
say ""
say "Upload it to the organisation's catalogue (needs the Teams administrator role):"
open_url "https://admin.teams.microsoft.com/policies/manage-apps"
step "Click 'Upload new app' (in some layouts it sits under 'Actions'), then choose the zip above."
step "When it lists Code Reviewer, make sure its status is Allowed."
say ""
say "Then install it for the developers, so the bot can write to them first:"
open_url "https://admin.teams.microsoft.com/policies/app-setup"
step "Open the policy the developers have (Global (Org-wide default) if nobody set another)."
step "Under 'Installed apps', click 'Add apps', search for Code Reviewer, Add, then Save."
note "Teams takes from minutes to a few hours to push a setup policy to everybody."
note "Without the admin role: Teams → Apps → Manage your apps → Upload an app installs it only for you."
pause "Done uploading?"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Second test: a direct message in Teams"
open_url "https://teams.microsoft.com/l/chat/0/0?users=28:$BOT_APP_ID"
step "If Teams asks, add the Code Reviewer app."
step "Write to the bot: hola"
say "Watching the queue for three minutes again."
if node scripts/drain.js --reply --wait 180; then
  step "Teams should now show 'Recibido: hola'."
  confirm "Did the answer arrive in Teams?" || warn "Note what Teams showed; the log above says what this Mac sent."
else
  warn "Nothing arrived from Teams. If Web Chat worked, the app is probably not installed for you yet."
fi

# ── 11 ────────────────────────────────────────────────────────────────────
stage "What Smart Terminal needs"
say "All of it is in $ENV_FILE (readable only by you). Nothing secret is printed here."
say ""
say "Tenant            $AZ_TENANT_ID"
say "Bot app id        $BOT_APP_ID"
say "Bot secret        saved, expires $(_existing BOT_APP_SECRET_EXPIRES || echo '?')"
say "Queue             $(_existing QUEUE_URL)"
say "Queue key         saved, read + remove only, expires $(_existing QUEUE_SAS_EXPIRES)"
say "Bot endpoint      $BOT_ENDPOINT"
say ""
note "Keep the Mac out of it: the Function answers Teams even when the laptop is asleep,"
note "and whatever arrives waits on the queue for up to seven days."
pause "Finish?"

finish
