import type { ITheme } from '@xterm/xterm';

export interface TerminalPalette {
  id: string;
  name: string;
  /** Whether this palette expects a light or dark surface around it. */
  mode: 'light' | 'dark';
  theme: ITheme;
}

/**
 * Terminal palettes. The colours a terminal draws are separate from the app's
 * chrome — someone can want a light interface around a dark terminal, which is a
 * common way to work — so the two are chosen independently, with "follow the app"
 * as the default for people who do not care.
 */
export const PALETTES: TerminalPalette[] = [
  {
    id: 'midnight',
    name: 'Midnight',
    mode: 'dark',
    theme: {
      background: '#0f1117',
      foreground: '#c8d0e0',
      cursor: '#7aa2f7',
      cursorAccent: '#0f1117',
      selectionBackground: '#2c3550',
      black: '#1a1c25',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#565f89',
      brightRed: '#ff7a93',
      brightGreen: '#b9f27c',
      brightYellow: '#ff9e64',
      brightBlue: '#7da6ff',
      brightMagenta: '#bb9af7',
      brightCyan: '#0db9d7',
      brightWhite: '#d5d6db',
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    mode: 'light',
    theme: {
      background: '#fbfbfa',
      foreground: '#33373f',
      cursor: '#2f6fdd',
      cursorAccent: '#fbfbfa',
      selectionBackground: '#cfdcf5',
      black: '#3b3f47',
      red: '#c0384c',
      green: '#3f7f3a',
      yellow: '#9a6a12',
      blue: '#2f6fdd',
      magenta: '#8a4bbd',
      cyan: '#1f7f8f',
      white: '#7c828d',
      brightBlack: '#9aa0aa',
      brightRed: '#d84a5e',
      brightGreen: '#4d9946',
      brightYellow: '#b8801a',
      brightBlue: '#4a86ec',
      brightMagenta: '#a05fd6',
      brightCyan: '#2596a8',
      brightWhite: '#33373f',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    mode: 'dark',
    theme: {
      background: '#002b36',
      foreground: '#93a1a1',
      cursor: '#93a1a1',
      cursorAccent: '#002b36',
      selectionBackground: '#073642',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#586e75',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    mode: 'light',
    theme: {
      background: '#fdf6e3',
      foreground: '#657b83',
      cursor: '#657b83',
      cursorAccent: '#fdf6e3',
      selectionBackground: '#eee8d5',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
  },
  {
    id: 'graphite',
    name: 'Graphite',
    mode: 'dark',
    theme: {
      background: '#141414',
      foreground: '#d4d4d4',
      cursor: '#e5e5e5',
      cursorAccent: '#141414',
      selectionBackground: '#3a3a3a',
      black: '#1f1f1f',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#d7ba7d',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#bdbdbd',
      brightBlack: '#5c5c5c',
      brightRed: '#ef7b85',
      brightGreen: '#a9d48a',
      brightYellow: '#e5c890',
      brightBlue: '#74bdf5',
      brightMagenta: '#d58ae8',
      brightCyan: '#6cc7d2',
      brightWhite: '#f0f0f0',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    mode: 'dark',
    theme: {
      background: '#2a303c',
      foreground: '#d8dee9',
      cursor: '#88c0d0',
      cursorAccent: '#2a303c',
      selectionBackground: '#434c5e',
      black: '#3b4252',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#e5e9f0',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    mode: 'dark',
    theme: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      cursor: '#f5e0dc',
      cursorAccent: '#1e1e2e',
      selectionBackground: '#45475a',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#f5c2e7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#f5c2e7',
      brightCyan: '#94e2d5',
      brightWhite: '#a6adc8',
    },
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    mode: 'dark',
    theme: {
      background: '#191724',
      foreground: '#e0def4',
      cursor: '#e0def4',
      cursorAccent: '#191724',
      selectionBackground: '#403d52',
      black: '#26233a',
      red: '#eb6f92',
      green: '#31748f',
      yellow: '#f6c177',
      blue: '#9ccfd8',
      magenta: '#c4a7e7',
      cyan: '#ebbcba',
      white: '#e0def4',
      brightBlack: '#6e6a86',
      brightRed: '#eb6f92',
      brightGreen: '#31748f',
      brightYellow: '#f6c177',
      brightBlue: '#9ccfd8',
      brightMagenta: '#c4a7e7',
      brightCyan: '#ebbcba',
      brightWhite: '#e0def4',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    mode: 'dark',
    theme: {
      background: '#1d2021',
      foreground: '#ebdbb2',
      cursor: '#ebdbb2',
      cursorAccent: '#1d2021',
      selectionBackground: '#504945',
      black: '#282828',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#a89984',
      brightBlack: '#928374',
      brightRed: '#fb4934',
      brightGreen: '#b8bb26',
      brightYellow: '#fabd2f',
      brightBlue: '#83a598',
      brightMagenta: '#d3869b',
      brightCyan: '#8ec07c',
      brightWhite: '#ebdbb2',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    mode: 'dark',
    theme: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      cursorAccent: '#282a36',
      selectionBackground: '#44475a',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    mode: 'light',
    theme: {
      background: '#eff1f5',
      foreground: '#4c4f69',
      cursor: '#dc8a78',
      cursorAccent: '#eff1f5',
      selectionBackground: '#ccd0da',
      black: '#5c5f77',
      red: '#d20f39',
      green: '#40a02b',
      yellow: '#df8e1d',
      blue: '#1e66f5',
      magenta: '#ea76cb',
      cyan: '#179299',
      white: '#acb0be',
      brightBlack: '#6c6f85',
      brightRed: '#d20f39',
      brightGreen: '#40a02b',
      brightYellow: '#df8e1d',
      brightBlue: '#1e66f5',
      brightMagenta: '#ea76cb',
      brightCyan: '#179299',
      brightWhite: '#bcc0cc',
    },
  },
  {
    id: 'rose-pine-dawn',
    name: 'Rosé Pine Dawn',
    mode: 'light',
    theme: {
      background: '#faf4ed',
      foreground: '#575279',
      cursor: '#575279',
      cursorAccent: '#faf4ed',
      selectionBackground: '#dfdad9',
      black: '#575279',
      red: '#b4637a',
      green: '#286983',
      yellow: '#ea9d34',
      blue: '#56949f',
      magenta: '#907aa9',
      cyan: '#d7827e',
      white: '#9893a5',
      brightBlack: '#797593',
      brightRed: '#b4637a',
      brightGreen: '#286983',
      brightYellow: '#ea9d34',
      brightBlue: '#56949f',
      brightMagenta: '#907aa9',
      brightCyan: '#d7827e',
      brightWhite: '#cecacd',
    },
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    mode: 'light',
    theme: {
      background: '#ffffff',
      foreground: '#1f2328',
      cursor: '#0969da',
      cursorAccent: '#ffffff',
      selectionBackground: '#b6e3ff',
      black: '#24292f',
      red: '#cf222e',
      green: '#116329',
      yellow: '#4d2d00',
      blue: '#0969da',
      magenta: '#8250df',
      cyan: '#1b7c83',
      white: '#6e7781',
      brightBlack: '#57606a',
      brightRed: '#a40e26',
      brightGreen: '#1a7f37',
      brightYellow: '#633c01',
      brightBlue: '#218bff',
      brightMagenta: '#a475f9',
      brightCyan: '#3192aa',
      brightWhite: '#8c959f',
    },
  },
];

export const FOLLOW_APP = 'follow-app';

/** The keys a person is actually likely to want to change by hand. */
export const OVERRIDABLE = [
  { key: 'background', label: 'Background' },
  { key: 'foreground', label: 'Text' },
  { key: 'cursor', label: 'Cursor' },
  { key: 'selectionBackground', label: 'Selection' },
] as const;

export type OverridableKey = (typeof OVERRIDABLE)[number]['key'];

export function paletteById(id: string): TerminalPalette | undefined {
  return PALETTES.find((palette) => palette.id === id);
}

/**
 * The palette to draw with, given the chosen id and the palette the interface
 * theme brings with it — which is what "follow the interface" follows.
 */
export function resolveTerminalTheme(
  paletteId: string,
  overrides: Partial<Record<OverridableKey, string>>,
  followPaletteId: string,
): ITheme {
  const base =
    paletteId === FOLLOW_APP
      ? (paletteById(followPaletteId) ?? PALETTES[0])
      : (paletteById(paletteId) ?? PALETTES[0]);

  const theme: ITheme = { ...base.theme };
  for (const [key, value] of Object.entries(overrides)) {
    if (value) (theme as Record<string, unknown>)[key] = value;
  }
  // The cursor's contrasting colour has to track the background it sits on.
  if (overrides.background) theme.cursorAccent = overrides.background;
  return theme;
}
